

server {
    listen 80;
    server_name localhost;

# 1. 增加上传文件大小限制 (AI平台传数据集必须配这个)
    client_max_body_size 1024M;

# --- 转发后端 API ---
    location /api/ {
        # 这里的 host.docker.internal 指向宿主机
        proxy_pass http://host.docker.internal:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /media/ {
        # 这里的 host.docker.internal 指向宿主机
        proxy_pass http://host.docker.internal:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


# --- Jupyter 转发 (保持之前的逻辑) ---
    # 1. 核心：配置 Docker 内置 DNS 解析器
    # Docker 容器内部 DNS 固定为 127.0.0.11
    resolver 127.0.0.11 valid=10s;

    # 2. 匹配 /lab/u{user_id}_e{exp_id}/...
    # 正则提取容器名 (container_name)
    location ~ ^/lab/(?<container_name>[\w-]+)/ {

        # 3. 动态代理到容器内部 8888 端口
        # 注意：这里使用变量时，必须有 resolver 支持
        proxy_pass http://$container_name:8888;

        # 标准 WebSocket 和 Header 配置
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # 增加超时防止 Jupyter 启动慢导致 504
        proxy_connect_timeout 60s;
        proxy_read_timeout 86400s;
    }


}


